@startuml "Concessionária"

class Pessoa{
    -nomeCompleto: String
    -cpf: String
    -idade: int
    -endereco: String
    -email: String
}

class Vendedor{
    -salario: double
    -comissao: double
    +criarVendedor()
    +lerVendedor()
    +atualizarVendedor()
    +excluirVendedor()
    +calcularSalario()
}
class Cliente{
    -renda:double
    +criarCliente()
    +lerCliente()
    +atualizarCliente()
    +excluirCliente()
    +realizarPagamento()
    +solicitarVeiculo()
}

class Veiculo{
    -marca: String 
    -modelo: String
    -anoDeFabricacao:int 
    -cor: String 
    -estadoDoVeiculo: String
    -quantidade:int
    +criarVeiculo()
    +lerVeiculo()
    +atualizarVeiculo()
    +excluirVeiculo()
    +listarVeiculos()
    +atualizarEstoque()
}
class Venda{
    -status: String
    -valor: double 
    -data: String
    -veiculo: Veiculo
    -cliente: Cliente
    -vendedor: Vendedor
    +criarVenda()
    +lerVenda()
    +atualizarVenda()
    +excluirVenda()
    +listarVenda()
    +criarSolicitacao() 
    +listarSolicitacoesPententes()
    +listarRegistroDeVendas()
    +excluirSolicitacao()
}
Pessoa <|-- Vendedor
Pessoa <|-- Cliente 

Vendedor "1"--"0...*" Venda: realiza >
Venda "0...*" -- "1...*" Veiculo: possui >
Venda "0...*" -- "1" Cliente: possui >

@enduml